version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:13
    restart: always
    ports:
      - "5499:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
